name: Nightly builds

on:
  schedule:
    # Run at 5:30 am, daily.
    - cron: '15 5 * * *'
  workflow_dispatch:

env:
  RUST_BACKTRACE: 1
  SHELL: /bin/bash

jobs:
  upload-win:
    name: Upload nightly (Windows)
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Copy to C drive
        run: cp D:\a C:\ -Recurse
      - name: Bootstrap
        working-directory: "C:\\a\\servo\\servo"
        run: |
          python -m pip install --upgrade pip virtualenv
          python mach fetch
      - name: Release build
        working-directory: "C:\\a\\servo\\servo"
        run: python mach build --release --media-stack=dummy
      - name: Package
        working-directory: "C:\\a\\servo\\servo"
        run: python mach package --release
      - name: Upload
        working-directory: "C:\\a\\servo\\servo"
        run: python mach upload-nightly windows-msvc --secret-from-environment
        env:
          S3_UPLOAD_CREDENTIALS: ${{ secrets.S3_UPLOAD_CREDENTIALS }}
